# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21d6fac98e6bcac0892a20ec8a55303ce15f433770793c7a42797b727a023cabb6cfae930616fca58103918126f555873c5dd1eb5ee172622c0a9cf23bab163b

test:
  secret_key_base: 9d148997db5a33a2eec171a5a798ff513af5526b28ef06876e2a72ab46cf3365e9f2a098b994a443d89928aab6f5c2a31076a023e26258cade7da99e1393e995

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
